<?php
echo $this->doctype() ?>
<?php 
$this->headStyle()->appendStyle($this->baseUrl().'/js/jquery/css/ui-lightness/jquery-ui-custom.css');
?>
<html>

<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>
    <?php echo $this->jQuery();?>
    <base href="/" />
   
	<?php
	
		if ($this->custom_head) {
			echo $this->custom_head;
		}
	?>
</head>

<body id="page-home" <?php if ($this->custom_body) {
	echo $this->custom_body;
}?> >
    <h1>Admin</h1>
    <?php echo $this->layout()->content; ?>
</body>

</html>