<?php echo $this->doctype() ?>
<html>

<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>
    <?php echo $this->headLink()->appendStylesheet('css/styles.css');?>
    <base href="/" />
</head>

<body id="page-home">
    <?php echo $this->render('header.phtml') ?>
	<section id="main"><!-- #main content and sidebar area -->
			<section id="content"><!-- #content -->
			
        		<article>
							<h2><a href="#">First Interesting Article or Section Title</a></h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. <a href="#">Duis sagittis ipsum</a>. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet.  Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur sodales ligula in libero. Sed dignissim lacinia nunc. Duo partem graeco repudiare ne, vix cu graeci nostrud blandit. Agam graecis omnesque usu ut, veniam commune ne sit, vide lucilius complectitur at ius.</p> 
						</article>
						
						<article>
						<h2><a href="#">Title of 3-Column Quick Information Section</a></h2>
						  <div class="col1">
						  <img src="Mijntuinkalender/public/images/l1.png" alt="" />
              <p>Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla.</p>
              </div>

						  <div class="col2">
						  <img src="Mijntuinkalender/public/images/l2.png" alt="" />
              <p>Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla.</p>
              </div>

						  <div class="col3">
						  <img src="Mijntuinkalender/public/images/l3.png" alt="" />
              <p>Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla.</p>
              </div>
						</article>
						
        		<article>
							<h2><a href="#">Second Section or Article Title</a></h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur sodales ligula in libero. Sed dignissim lacinia nunc. Usu pericula argumentum repudiandae ea, ut vis deserunt oportere, assum nominavi percipitur ei ius. Nam timeam atomorum philosophia te, ut eum amet laoreet pertinax, an duo error aperiri reformidans. Et alii quas partiendo mei, wisi quaestio convenire et vix.</p>
						</article>
						
			</section><!-- end of #content -->

		<aside id="sidebar"><!-- sidebar -->
				<h3>Things To Do</h3>
					<ul>
						<li><a href="#">Play Games</a></li>
						<li><a href="#">Chat With Friends</a></li>
						<li><a href="#">Swap Stories</a></li>
						<li><a href="#">Sell Stuff</a></li>
						<li><a href="#">Buy Stuff</a></li>
						<li><a href="#">Trade Stuff</a></li>
					</ul>
					
				<h3>Sponsors</h3>
					<img src="Mijntuinkalender/public/images/ad180.png" alt="" /><br /><br />

				<h3>Connect With Us</h3>
					<ul>
						<li><a href="#">Twitter</a></li>
						<li><a href="#">Facebook</a></li>
						<li><a href="#">LinkedIn</a></li>
						<li><a href="#">Flickr</a></li>
					</ul>
					
				<h3>Did You Know?</h3>
					<ul>
						<li><a href="#">Curabitur sodales</a></li>
						<li><a href="#">Sed dignissim</a></li>
						<li><a href="#">Fusce nec</a></li>
						<li><a href="#">Nulla quis</a></li>
						<li><a href="#">Curabitur sodales</a></li>
						<li><a href="#">Sed dignissim</a></li>
						<li><a href="#">Fusce nec</a></li>
						<li><a href="#">Nulla quis</a></li>
					</ul>

		</aside><!-- end of sidebar -->

	</section><!-- end of #main content and sidebar-->
    <?php echo $this->render('footer.phtml') ?>

</body>

</html>