<?php echo $this->doctype() ?>
<html>

<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>
    <base href="/" />
</head>

<body id="page-home">
    <?php echo $this->render('header.phtml') ?>

    <h1>test</h1>
    <?php echo $this->render('footer.phtml') ?>

</body>

</html>