<?php echo $this->doctype() ?>
<html>

<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>
    <?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/styles.css');?>
    
    <base href="/" />
</head>

<body id="page-home">
    <?php echo $this->render('header.phtml') ?>
	<section id="main"><!-- #main content and sidebar area -->
			<section id="content"><!-- #content -->
				<?php echo $this->layout()->content;?>			
			</section><!-- end of #content -->

		<aside id="sidebar"><!-- sidebar -->
				<h3>Things To Do</h3>
					<ul>
						<li><a href="#">Play Games</a></li>
						<li><a href="#">Chat With Friends</a></li>
						<li><a href="#">Swap Stories</a></li>
						<li><a href="#">Sell Stuff</a></li>
						<li><a href="#">Buy Stuff</a></li>
						<li><a href="#">Trade Stuff</a></li>
					</ul>
					
				<h3>Sponsors</h3>
					<img src="Mijntuinkalender/public/images/ad180.png" alt="" /><br /><br />

				<h3>Connect With Us</h3>
					<ul>
						<li><a href="#">Twitter</a></li>
						<li><a href="#">Facebook</a></li>
						<li><a href="#">LinkedIn</a></li>
						<li><a href="#">Flickr</a></li>
					</ul>
					
				<h3>Did You Know?</h3>
					<ul>
						<li><a href="#">Curabitur sodales</a></li>
						<li><a href="#">Sed dignissim</a></li>
						<li><a href="#">Fusce nec</a></li>
						<li><a href="#">Nulla quis</a></li>
						<li><a href="#">Curabitur sodales</a></li>
						<li><a href="#">Sed dignissim</a></li>
						<li><a href="#">Fusce nec</a></li>
						<li><a href="#">Nulla quis</a></li>
					</ul>

		</aside><!-- end of sidebar -->

	</section><!-- end of #main content and sidebar-->
    <?php echo $this->render('footer.phtml') ?>

</body>

</html>