	<div id="wrapper"><!-- #wrapper -->
	<header><!-- header -->
		<h1><a href="Mijntuinkalender/public/">Mijn Tuinkalender</a></h1>
		<?php 
			if ($this->loggedInAs()){
		?>	
			<div id="loggedin">
				<?php echo $this->loggedInAs();?>
			</div>
		<?php 
		}
			else {
		?>
			<div id="login">
				<?php echo $this->loginForm;?>
				<a href="<?= $this->url(array('controller'=>'index', 'action'=>'registration')) ;?>" >Registreren</a>
			</div>
		<?php 
			}
		?>
		<img src="Mijntuinkalender/public/images/headerimg.png" width="940" height="200" alt=""><!-- header image -->
	</header><!-- end of header -->
	
	<nav><!-- top nav -->
		<div class="menu">
			<ul>
				<li><a href="<?= $this->url(array('controller'=>'index', 'action'=>'index')) ;?>">Home</a></li>
				<li><a href="<?= $this->url(array('controller'=>'moestuin', 'action'=>'index')) ;?>">Moestuin</a></li>
				<li><a href="#">Kruidentuin</a></li>
				<li><a href="#">Forum</a></li>
				<?php if ($this->loggedInAs()) {?>
					<li><a href="#">Mijn Tuin</a></li>
				<?php }?>
				<li><a href="#"></a></li>
			</ul>
		</div>
	</nav><!-- end of top nav -->