	<div id="wrapper"><!-- #wrapper -->
	<header><!-- header -->
		<h1><a href="#">Mijn Tuinkalender</a></h1>
		<h2>Inloggen</h2>
		<img src="Mijntuinkalender/public/images/headerimg.jpg" width="940" height="200" alt=""><!-- header image -->
	</header><!-- end of header -->
	
	<nav><!-- top nav -->
		<div class="menu">
			<ul>
				<li><a href="#">Home</a></li>
				<li><a href="#">Moestuin</a></li>
				<li><a href="#">Kruidentuin</a></li>
				<li><a href="#">Forum</a></li>
				<li><a href="#"></a></li>
				<li><a href="#"></a></li>
			</ul>
		</div>
	</nav><!-- end of top nav -->