<?php
$this->title = "Nieuwe bewerking voor plant toevoegen";
$this->headTitle($this->title);
$this->custom_head .= '<script src="'.$this->baseUrl().'/js/ckeditor/ckeditor.js" type="text/javascript"></script><script language="javascript" type="text/javascript" src="'.$this->baseUrl().'/js/customs.js"></script>';
$this->custom_body .= ' onload="setupCK();"';
echo "<H2>Bestaande bewerkingen</H2>";
foreach ($this->existingBewerkingen as $existingBewerking):
	$bewerking = $existingBewerking['bewerking'];
	echo "$bewerking <br/>";
endforeach;
echo $this->form;
?>
