<?php
$this->title = "Plant bewerken";
$this->headTitle($this->title);
$this->custom_head .= '<script src="'.$this->baseUrl().'/js/ckeditor/ckeditor.js" type="text/javascript"></script><script language="javascript" type="text/javascript" src="'.$this->baseUrl().'/js/customs.js"></script>';
$this->custom_body .= ' onload="setupCK();"';
echo $this->form ;
?>

<P>Huidige afbeelding</P>
<?php 

$afbeelding = $this->baseUrl().'/images/'.$this->planten['afbeelding'];

?>
<img src="../MijnTuinkalender/library/phpThumb/phpthumb.php?src=<?php echo $afbeelding;?>&w=125&f=jpg>"/>